# Generated by Django 5.2.4 on 2025-08-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='cookie_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
