# Generated by Django 5.2.4 on 2025-08-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_bot', '0002_facebookaccount_cookie_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookaction',
            name='post',
        ),
        migrations.AddField(
            model_name='facebookaction',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
