# Generated by Django 5.2.4 on 2025-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_bot', '0003_remove_facebookaction_post_facebookaction_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
