# Generated by Django 5.2.4 on 2025-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_bot', '0004_facebookaccount_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facebookaction',
            name='action',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('like_comment', 'Like and Comment'), ('share', 'Share'), ('like_comment_share', 'Like, Comment and Share')], max_length=30),
        ),
    ]
