# Generated by Django 5.2.4 on 2025-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_bot', '0005_facebookaccount_last_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginRequiredAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
